services:
  - type: web
    name: devops-real-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ORIGIN
        value: "*"
