name: CI & Deploy
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18', cache: 'npm' }
      - run: npm ci
      - run: npm test -- --ci
      - name: Deploy via Deploy Hook (preferred)
        if: ${{ success() && secrets.DEPLOY_HOOK_URL != '' }}
        run: curl -sS -X POST "${{ secrets.DEPLOY_HOOK_URL }}"
      - name: Deploy via Render API (fallback)
        if: ${{ success() && (secrets.DEPLOY_HOOK_URL == '' || secrets.DEPLOY_HOOK_URL == null) && secrets.RENDER_API_KEY != '' && secrets.RENDER_SERVICE_ID != '' }}
        run: |
          curl -sS -X POST             -H "Accept: application/json"             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"             "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
